// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHB3XDtGLegJnqak1H8upwTOfFrJxRD6U',
    appId: '1:332401986518:web:5196d5d5cb408d71fa7277',
    messagingSenderId: '332401986518',
    projectId: 'whatsapp-27924',
    authDomain: 'whatsapp-27924.firebaseapp.com',
    storageBucket: 'whatsapp-27924.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiaGqzLdzB60YSMjMBsJM6m0HRfltmKgg',
    appId: '1:332401986518:android:eab72e856afb4339fa7277',
    messagingSenderId: '332401986518',
    projectId: 'whatsapp-27924',
    storageBucket: 'whatsapp-27924.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5bZ0xmRStdqPDuv7fYLh-cLUWujSz--E',
    appId: '1:332401986518:ios:38637dd4c21e028bfa7277',
    messagingSenderId: '332401986518',
    projectId: 'whatsapp-27924',
    storageBucket: 'whatsapp-27924.appspot.com',
    iosClientId: '332401986518-iejgrt27n841q78htua5f59mbi3i8nee.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5bZ0xmRStdqPDuv7fYLh-cLUWujSz--E',
    appId: '1:332401986518:ios:38637dd4c21e028bfa7277',
    messagingSenderId: '332401986518',
    projectId: 'whatsapp-27924',
    storageBucket: 'whatsapp-27924.appspot.com',
    iosClientId: '332401986518-iejgrt27n841q78htua5f59mbi3i8nee.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsapp',
  );
}
